# Generated by Django 2.2.4 on 2019-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='drawing1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='drawing2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactlensprescription',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactlensprescription',
            name='color',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='contactlensprescription',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactlensprescription',
            name='replacement_schedule',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='glassesprescription',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='consent_hipaa',
            field=models.NullBooleanField(default=False, verbose_name='Consent to HIPAA privacy policy'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='consent_tcpa',
            field=models.NullBooleanField(default=False, verbose_name='Consent to text messages'),
        ),
    ]
