# Generated by Django 2.2.2 on 2019-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190814_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='drawing1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comprehensiveexam',
            name='drawing2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactlensprescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='glassesprescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='glassesprescription',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d'),
        ),
    ]
