# Generated by Django 2.2.2 on 2019-08-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190814_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypercholesterolemia',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
