# Generated by Django 2.2.2 on 2019-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190815_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='here',
            field=models.BooleanField(default=False, help_text='Is the patient here right now?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(db_index=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Nonbinary'), ('U', 'Decline to state')], default='U', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='phone 2'),
        ),
    ]
