# Generated by Django 2.2.2 on 2019-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190815_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprehensiveexam',
            name='old_prescription',
        ),
        migrations.AlterField(
            model_name='patient',
            name='here',
            field=models.BooleanField(db_index=True, default=False, help_text='Is the patient here right now?'),
        ),
    ]
