# Generated by Django 2.2.4 on 2019-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190815_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='called',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='can_call',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='last_name',
        ),
        migrations.AddField(
            model_name='comprehensiveexam',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlensprescription',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='glassesprescription',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='glassesprescription',
            name='va_left',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VA left'),
        ),
        migrations.AlterField(
            model_name='glassesprescription',
            name='va_right',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VA right'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Nonbinary'), ('u', 'Decline to state')], default='u', max_length=1, verbose_name='gender'),
        ),
    ]
